# Generated by Django 4.1.7 on 2023-03-20 09:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0004_alter_review_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Review_movie',
        ),
    ]
